"""
Django settings for setup project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from datetime import timedelta

import dj_database_url

from .env import BASE_DIR, ENV_BOOL, ENV_LIST, ENV_NUM, ENV_STR, PARDIR  # noqa

SECRET_KEY = ENV_STR("SECRET_KEY")

FERNET_SECRET_KEY = ENV_STR("FERNET_SECRET_KEY")

DEBUG = ENV_BOOL("DEBUG")

ALLOWED_HOSTS = ENV_LIST("ALLOWED_HOSTS", ",", ["*"] if DEBUG else [])

CSRF_TRUSTED_ORIGINS = ENV_LIST("CSRF_TRUSTED_ORIGINS", ",", [])

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = ENV_LIST("CORS_ALLOWED_ORIGINS", ",", [])

# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    # 3rd party:
    "corsheaders",
    "rest_framework",
    "rest_framework_gis",
    "django_filters",
    "drf_yasg",
    "leaflet",
    # Custom apps:
    "accounts",
    "efeo",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "setup.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "setup.wsgi.application"

ASGI_APPLICATION = "setup.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {"default": dj_database_url.config()}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Substituting a custom User model
AUTH_USER_MODEL = "accounts.User"

# Define DRF settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 20,
}

# # # AUTH SETTINGS

AUTH_AUTHENTICATION_METHOD = "email"  # Options: username | email | username_email
AUTH_EMAIL_REQUIRED = True
AUTH_USERNAME_REQUIRED = False  # Require username in registration
AUTH_EMAIL_VERIFICATION = "mandatory"  # <mandatory|optional|None>
AUTH_ACCESS_TOKEN_NAME = "access"  # set access token name
AUTH_REFRESH_TOKEN_NAME = "refresh"  # set access token name

# Simple JWT config

SIMPLE_JWT = {
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=ENV_NUM("JWT_REFRESH_TOKEN_LIFETIME_DAYS", 15)
    ),
    "ROTATE_REFRESH_TOKENS": True,
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=(
            15 * 24 * 60
            if ENV_BOOL("DEBUG") is True
            else ENV_NUM("JWT_ACCESS_TOKEN_LIFETIME_MINUTES", 5)
        )
    ),
    "AUTH_COOKIE_SECURE": True,
    "AUTH_COOKIE_SAMESITE": "None",
    "AUTH_COOKIE_HTTP_ONLY": True,
}

# API docs
SHOW_API_DOCS = ENV_BOOL("SHOW_API_DOCS", True)


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
DEFAULT_STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_ROOT = ENV_STR("STATIC_ROOT", DEFAULT_STATIC_ROOT)
STATICFILES_DIRS = []

# Data dir
DATA_DIR = ENV_STR("DATA_DIR", os.path.join(BASE_DIR, "data"))
DATA_URL = ENV_STR("DATA_URL", "/data/")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# This API details
API_BASE_URL = ENV_STR("API_BASE_URL")
API_SECRET_KEY = ENV_STR("API_SECRET_KEY")

# Swagger settings
SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "JWT": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
        },
    },
    "USE_SESSION_AUTH": False,
    "JSON_EDITOR": True,  # Enable the JSON editor for request/response bodies
}

# ENV settings for proj and gdal
PROJ_LIB = ENV_STR("PROJ_LIB", None)
GDAL_DATA = ENV_STR("GDAL_DATA", None)

if PROJ_LIB:
    os.environ["PROJ_LIB"] = PROJ_LIB

if GDAL_DATA:
    os.environ["GDAL_DATA"] = GDAL_DATA

# Logging settings
DEFAULT_LOG_DIR = ENV_STR("DEFAULT_LOG_DIR")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {"handlers": ["console"], "level": "INFO"},
}


LEAFLET_CONFIG = {
    "SPATIAL_EXTENT": (-140.99778, 41.6751050889, -52.6480987209, 83.23324),
    "DEFAULT_CENTER": (43.6532, -79.3832),
    "DEFAULT_ZOOM": 12,
    "MIN_ZOOM": 4,
    "MAX_ZOOM": 20,
    "DEFAULT_PRECISION": 6,
}
