# Generated by Django 5.1.1 on 2024-10-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efeo', '0013_worksitetype_worksite'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Trench',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
