# Generated by Django 5.1.1 on 2024-10-05 21:25

import django.db.models.deletion
import efeo.models
import setup.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efeo', '0015_alter_fieldseason_options_alter_map_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorksiteResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=128)),
                ('resource_date', models.DateField(blank=True, null=True)),
                ('resource_file', models.FileField(max_length=255, storage=setup.storage.DataStorage(), upload_to=efeo.models.get_site_resource_dir)),
                ('gcs_id', models.PositiveIntegerField(blank=True, null=True)),
                ('context', models.CharField(blank=True, max_length=128)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fieldseason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='efeo.fieldseason')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='efeo.worksiteresourcetype')),
                ('trench', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='efeo.trench')),
                ('worksite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='efeo.worksite')),
            ],
            options={
                'verbose_name': 'WorkSite Resource',
                'verbose_name_plural': 'WorkSite Resources',
            },
        ),
    ]
