# Generated by Django 5.1.1 on 2024-09-22 13:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efeo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
