# Generated by Django 5.1.1 on 2024-09-22 13:49

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efeo', '0004_sitetype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('english_name', models.CharField(max_length=255)),
                ('french_name', models.CharField(blank=True, max_length=255)),
                ('khmer_name', models.CharField(blank=True, max_length=255)),
                ('alternative_name', models.CharField(blank=True, max_length=255)),
                ('alternative_khmer_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('ik_id_starred', models.BooleanField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='efeo.map')),
                ('site_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='efeo.sitetype')),
            ],
        ),
    ]
