# Generated by Django 5.1.1 on 2024-09-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efeo', '0006_mapnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
