# Generated by Django 5.1.1 on 2024-09-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efeo', '0007_map_deleted_at_site_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WmsLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=128)),
                ('abstract', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('wms_url', models.URLField(max_length=255)),
                ('image_type', models.CharField(choices=[('jpeg', 'jpeg'), ('png', 'png')], default='png', max_length=32)),
                ('layer_type', models.CharField(choices=[('VECTOR', 'VECTOR'), ('RASTER', 'RASTER')], default='VECTOR', max_length=64)),
                ('use_as_tile_layer', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='XYZLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=128)),
                ('abstract', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('tiles_url', models.URLField(verbose_name='Tiles URL')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
