# Generated by Django 5.1.1 on 2024-09-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efeo', '0008_wmslayer_xyzlayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='VectorTileLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=128)),
                ('abstract', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('tiles_url', models.URLField(max_length=255, verbose_name='Tiles URL')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='xyzlayer',
            name='tiles_url',
            field=models.URLField(max_length=255, verbose_name='Tiles URL'),
        ),
    ]
