# Generated by Django 5.1.1 on 2024-09-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efeo', '0009_vectortilelayer_alter_xyzlayer_tiles_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='vector_tile_layers',
            field=models.ManyToManyField(blank=True, to='efeo.vectortilelayer'),
        ),
        migrations.AddField(
            model_name='map',
            name='wms_layers',
            field=models.ManyToManyField(blank=True, to='efeo.wmslayer'),
        ),
        migrations.AddField(
            model_name='map',
            name='xyz_layers',
            field=models.ManyToManyField(blank=True, to='efeo.xyzlayer'),
        ),
    ]
