# Generated by Django 5.1.1 on 2024-09-30 19:57

import django.db.models.deletion
import efeo.models
import setup.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efeo', '0010_map_vector_tile_layers_map_wms_layers_map_xyz_layers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='WorksiteResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SiteResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=128)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('resource_date', models.DateField(blank=True, null=True)),
                ('resource_file', models.FileField(max_length=255, storage=setup.storage.DataStorage(), upload_to=efeo.models.get_site_resource_dir)),
                ('notes', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='efeo.site')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='efeo.siteresourcetype')),
            ],
        ),
    ]
