# Generated by Django 5.1.1 on 2024-10-01 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('efeo', '0011_siteresourcetype_worksiteresourcetype_siteresource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteresource',
            old_name='added_by',
            new_name='created_by',
        ),
    ]
