# Generated by Django 5.1.1 on 2024-10-03 14:11

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efeo', '0012_rename_added_by_siteresource_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorksiteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Worksite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=128)),
                ('method', models.CharField(max_length=16)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('looted', models.BooleanField(null=True)),
                ('cultivated', models.BooleanField(null=True)),
                ('cleared', models.BooleanField(null=True)),
                ('threatened', models.BooleanField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('archsite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worksites', to='efeo.site')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_worksites', to=settings.AUTH_USER_MODEL)),
                ('worksite_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='efeo.worksitetype')),
            ],
        ),
    ]
