# Generated by Django 5.1.1 on 2024-10-05 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('efeo', '0014_fieldseason_trench'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldseason',
            options={'verbose_name': 'Field Season', 'verbose_name_plural': 'Field Seasons'},
        ),
        migrations.AlterModelOptions(
            name='map',
            options={'verbose_name': 'Map', 'verbose_name_plural': 'Maps'},
        ),
        migrations.AlterModelOptions(
            name='mapconfig',
            options={'verbose_name_plural': 'Map Layer Configurations'},
        ),
        migrations.AlterModelOptions(
            name='mapnote',
            options={'verbose_name': 'Map Note', 'verbose_name_plural': 'Map Notes'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Arch Site', 'verbose_name_plural': 'Arch Sites'},
        ),
        migrations.AlterModelOptions(
            name='siteresource',
            options={'verbose_name': 'Arch Site Resource', 'verbose_name_plural': 'Arch Site Resources'},
        ),
        migrations.AlterModelOptions(
            name='siteresourcetype',
            options={'verbose_name': 'Arch Site Resource Type', 'verbose_name_plural': 'Arch Site Resource Types'},
        ),
        migrations.AlterModelOptions(
            name='sitetype',
            options={'verbose_name': 'Arch Site Type', 'verbose_name_plural': 'Arch Site Types'},
        ),
        migrations.AlterModelOptions(
            name='trench',
            options={'verbose_name': 'Trench', 'verbose_name_plural': 'Trenches'},
        ),
        migrations.AlterModelOptions(
            name='worksite',
            options={'verbose_name': 'Worksite', 'verbose_name_plural': 'Worksites'},
        ),
        migrations.AlterModelOptions(
            name='worksiteresourcetype',
            options={'verbose_name': 'Worksite Resource', 'verbose_name_plural': 'Worksite Resources'},
        ),
        migrations.AlterModelOptions(
            name='worksitetype',
            options={'verbose_name': 'Worksite Type', 'verbose_name_plural': 'Worksite Types'},
        ),
    ]
