# Generated by Django 5.1.1 on 2024-10-05 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('efeo', '0016_worksiteresource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vectortilelayer',
            options={'verbose_name': 'Layers - Vector Tiles', 'verbose_name_plural': 'Layers - Vector Tiles'},
        ),
        migrations.AlterModelOptions(
            name='wmslayer',
            options={'verbose_name': 'Layers - WMS', 'verbose_name_plural': 'Layers - WMS'},
        ),
        migrations.AlterModelOptions(
            name='worksiteresource',
            options={'verbose_name': 'Worksite Resource', 'verbose_name_plural': 'Worksite Resources'},
        ),
        migrations.AlterModelOptions(
            name='worksiteresourcetype',
            options={'verbose_name': 'Worksite Resource Type', 'verbose_name_plural': 'Worksite Resource Types'},
        ),
        migrations.AlterModelOptions(
            name='xyzlayer',
            options={'verbose_name': 'Layers - XYZ', 'verbose_name_plural': 'Layers - XYZ'},
        ),
    ]
