# Generated by Django 5.1.1 on 2024-10-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efeo', '0018_alter_mapconfig_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individuals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Individual',
                'verbose_name_plural': 'Individuals',
            },
        ),
        migrations.RemoveField(
            model_name='siteresource',
            name='author',
        ),
    ]
