# Generated by Django 5.1.1 on 2024-10-08 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efeo', '0019_individuals_remove_siteresource_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteresource',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='efeo.individuals'),
        ),
    ]
