# Generated by Django 5.1.1 on 2024-11-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efeo', '0020_siteresource_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='db_resolved',
            field=models.SmallIntegerField(null=True),
        ),
    ]
